name: miuivs_patch_build

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'Services.jar Url'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting up
        run: |
          sudo apt-get update && sudo apt-get install -y git wget zip unzip axel python3-pip zipalign apksigner xmlstarlet
          pip3 install ConfigObj

      - name: Set up Time
        run: |
          cd $GITHUB_WORKSPACE
          echo "Setting Vienam timezone"
          sudo timedatectl set-timezone Asia/Ho_Chi_Minh

      - name: Download Services.jar
        run: |
          axel -n $(nproc) ${{ github.event.inputs.ROM_URL }}

      - name: (Optional) Download bhlnk.sh script
        # Add a step to download or check out the bhlnk.sh script if necessary

      - name: PATCH-ING (Consider alternative permissions)
        run: |
          # Consider using a more restrictive permission setting instead of chmod 777
          ./bhlnk.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: services_patched_bhlnk.zip
          path: ./module/*
